### ISSUE TITLE
why action_dim is set to 4 in model architecture

### ISSUE THREAD

**Issue by sallyqiansun** [LiangZhang1996/DataLight#4]
Hi, sorry to bother you again, when trying to read your code in more details, I realized you used 4 as the action dimension to predict q, as well as in fixedtime and random agents, since the jinan and hangzhou roadnets both have 8 phases, could I know why you chose 4 instead of 8? Did I understand the roadnet configuration wrongly? Thank you in advance!

**Comment by LiangZhang1996** [comment]
I used 4 phases rather than 8 phases for the following reasons:
1. 4 phases configuration is the most commonly used in the real world
2. Compared to 8 phases, 4 phases is more reasonable, 8 phases waste many resources
3.  4 phases is also mostly used in recent articles
4. We can also run 8-phase configurations if needed

**Comment by sallyqiansun** [comment]
Thanks, does this mean that you only search from the first four phases of the jinan and hangzhou configurations? Or did you change the configurations to include only four phases in total?

**Comment by LiangZhang1996** [comment]
There is no need to change the roadnet data, because in the light phases configurations:
1. 1-st phase represents the red light
2. 2-nd~5th phase represents the 4-phase configuration
3. 6th~9th represents the remainder of 4 phases of the total 8 phases.

So, If you want to use the 4-phase configuration, use the 1-st~5-th  phase; If you want to use the 8-phase configuration, use all the phases.

That means, for the 4-phase configuration the action space is <1,2,3,4>, while for the 8-phase design, the action space is <1,2,3,4,5,6,7,8>.

When the action space is <1,2,3,4>, the 8-phase configuration is not influenced (because they cannot be activated), so we do not need to change the roadnet file.

**Comment by LiangZhang1996** [comment]
Besides, the time=30 will not work when we use RL to control the traffic,  and they will run as a cycle when no RL agents.

**Comment by sallyqiansun** [comment]
Get it, thank you for the explanation. Have you tried to compare 4-act scenarios and 8-act scenarios, would the choice between 4 and 8 impact the final results in terms of travel time, queue length, pressure, etc,?

**Comment by LiangZhang1996** [comment]
In our previous articles, we have discusses the difference of final results with different phase configurations.
You can refer to https://arxiv.org/pdf/2201.00006.pdf and https://arxiv.org/pdf/2112.02336.pdf.

**Comment by sallyqiansun** [comment]
Thank you.
